### ISSUE TITLE
Problem with path of pirdf in launcher.sh

### ISSUE THREAD

**Issue by GitEnjoyer-RandomNumberThatNoOneUsed** [gabiga7/pirdf#2]
Path of pirdf is hardcoded line 2, the user should start launcher.sh directly from pirdf

**Comment by gabiga7** [comment]
merge done, thank you

**Comment by GitEnjoyer-RandomNumberThatNoOneUsed** [comment]
> merge done, thank you

No problem sir.  😎😎😎
